[pytest]
DJANGO_SETTINGS_MODULE = artefact.settings
python_files = tests.py test_*.py *_tests.py
addopts = --reuse-db --no-migrations
markers =
    mock: marks tests that use mocked external services
    real: marks tests that use real external services
filterwarnings =
    ignore::DeprecationWarning
    ignore::django.utils.deprecation.RemovedInDjango60Warning