# Generated by Django 5.1.3 on 2025-01-09 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ronins', '0001_initial'),
        ('satoris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Main focus of the quest (e.g., 'Exploring Ancient Kyoto')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ronin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='ronins.ronin')),
                ('satori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidances', to='satoris.satori')),
            ],
        ),
    ]
