# Generated by Django 5.1.3 on 2024-12-22 12:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ronin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), help_text='List of travel interests', null=True, size=None)),
                ('style', models.TextField(help_text='Personal approach and characteristics', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ronin',
                'verbose_name_plural': 'Ronin',
            },
        ),
    ]
