# Generated by Django 5.1.3 on 2024-12-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ronin',
            name='travel_style',
        ),
        migrations.AddField(
            model_name='ronin',
            name='style',
            field=models.TextField(help_text='Personal approach and characteristics', null=True),
        ),
    ]
