# Generated by Django 5.1.3 on 2025-01-15 07:23

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The canonical name of this artefact', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', unique=True)),
                ('description', models.TextField(blank=True, help_text='Rich description combining various data sources', null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, help_text='Vector embedding for similarity search', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'artefact',
                'verbose_name_plural': 'artefacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtefactAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="The source of this attribute data (e.g., 'google_places', 'wikipedia')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtefactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When this data was fetched from the source')),
                ('raw_data', models.JSONField(help_text='The complete raw data from the source')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtefactEnrichmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('ArtefactGooglePlaceData', 'Google Places'), ('ArtefactWikipediaData', 'Wikipedia'), ('ArtefactWikidataData', 'Wikidata'), ('ArtefactTripAdvisorData', 'TripAdvisor')], help_text='The type of ArtefactData to create/update', max_length=50)),
                ('state', models.CharField(choices=[('PENDING', 'Task Pending'), ('IN_PROGRESS', 'Task Running'), ('COMPLETED', 'Task Completed'), ('FAILED', 'Task Failed')], default='PENDING', help_text='Current state of the enrichment task', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if the task failed', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of times this task has been retried')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the task started running', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task completed or failed', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
