# Generated by Django 5.1.3 on 2025-01-09 00:21

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artefacts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='source_entity',
            field=models.ForeignKey(help_text='The entity this artefact was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefacts', to='entities.entity'),
        ),
        migrations.CreateModel(
            name='ArtefactContact',
            fields=[
                ('artefactattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artefacts.artefactattribute')),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hours', models.JSONField(blank=True, help_text='Operating hours structure', null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('artefacts.artefactattribute',),
        ),
        migrations.CreateModel(
            name='ArtefactLocation',
            fields=[
                ('artefactattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artefacts.artefactattribute')),
                ('latitude', models.FloatField(help_text='Latitude coordinate')),
                ('longitude', models.FloatField(help_text='Longitude coordinate')),
                ('address', models.JSONField(blank=True, help_text='Structured address components', null=True)),
            ],
            bases=('artefacts.artefactattribute',),
        ),
        migrations.CreateModel(
            name='ArtefactMedia',
            fields=[
                ('artefactattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artefacts.artefactattribute')),
                ('url', models.URLField(help_text='URL to the media asset')),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('DOCUMENT', 'Document')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata about the media', null=True)),
            ],
            options={
                'verbose_name_plural': 'artefact media',
            },
            bases=('artefacts.artefactattribute',),
        ),
        migrations.CreateModel(
            name='ArtefactTemporalContext',
            fields=[
                ('artefactattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artefacts.artefactattribute')),
                ('start_date', models.DateTimeField(blank=True, help_text='When the artefact began existing or event started', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When the artefact ceased existing or event ended', null=True)),
                ('period_name', models.CharField(blank=True, help_text="Named period (e.g., 'Edo Period', 'Renaissance')", max_length=100, null=True)),
            ],
            bases=('artefacts.artefactattribute',),
        ),
        migrations.CreateModel(
            name='ArtefactWikidataRelation',
            fields=[
                ('artefactattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artefacts.artefactattribute')),
                ('property_id', models.CharField(help_text="The Wikidata property ID that establishes this relationship (e.g., 'P131')", max_length=20)),
                ('property_label', models.CharField(help_text="Human-readable label for the property (e.g., 'located in administrative territory')", max_length=100)),
                ('is_inverse', models.BooleanField(default=False, help_text='Whether this is an inverse relationship')),
                ('confidence', models.FloatField(help_text='Confidence score for this relationship (0-1)')),
                ('metadata', models.JSONField(blank=True, help_text='Additional context about the relationship', null=True)),
            ],
            bases=('artefacts.artefactattribute',),
        ),
        migrations.AddField(
            model_name='artefactattribute',
            name='artefact',
            field=models.ForeignKey(help_text='The artefact this attribute belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='artefacts.artefact'),
        ),
        migrations.AddField(
            model_name='artefactattribute',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='ArtefactGooglePlaceData',
            fields=[
                ('artefactdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artefacts.artefactdata')),
                ('place_id', models.CharField(help_text='Google Places unique identifier', max_length=255, unique=True)),
                ('rating', models.FloatField(blank=True, help_text='Google rating (0-5)', null=True)),
                ('rating_count', models.IntegerField(blank=True, help_text='Number of ratings', null=True)),
                ('price_level', models.IntegerField(blank=True, help_text='Price level (1-4)', null=True)),
            ],
            options={
                'verbose_name': 'Google Places data',
                'verbose_name_plural': 'Google Places data',
            },
            bases=('artefacts.artefactdata',),
        ),
        migrations.CreateModel(
            name='ArtefactTripAdvisorData',
            fields=[
                ('artefactdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artefacts.artefactdata')),
                ('location_id', models.CharField(help_text='TripAdvisor location identifier', max_length=50, unique=True)),
                ('rating', models.FloatField(blank=True, help_text='TripAdvisor rating (1-5)', null=True)),
                ('review_count', models.IntegerField(blank=True, help_text='Number of reviews', null=True)),
                ('ranking', models.CharField(blank=True, help_text="Ranking in category (e.g., '#5 of 100 restaurants in Tokyo')", max_length=255, null=True)),
                ('ranking_data', models.JSONField(blank=True, help_text='Structured ranking information', null=True)),
                ('awards', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, help_text="TripAdvisor awards (e.g., Travelers' Choice)", size=None)),
            ],
            options={
                'verbose_name': 'TripAdvisor data',
                'verbose_name_plural': 'TripAdvisor data',
            },
            bases=('artefacts.artefactdata',),
        ),
        migrations.CreateModel(
            name='ArtefactWikidataData',
            fields=[
                ('artefactdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artefacts.artefactdata')),
                ('entity_id', models.CharField(help_text='Wikidata Q identifier', max_length=20, unique=True)),
                ('wikidata_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), help_text='List of Wikidata Q IDs this entity is an instance of', size=None)),
                ('properties', models.JSONField(help_text='Structured Wikidata properties')),
            ],
            options={
                'verbose_name': 'Wikidata',
                'verbose_name_plural': 'Wikidata',
            },
            bases=('artefacts.artefactdata',),
        ),
        migrations.CreateModel(
            name='ArtefactWikipediaData',
            fields=[
                ('artefactdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artefacts.artefactdata')),
                ('page_id', models.IntegerField(help_text='Wikipedia page ID', unique=True)),
                ('url', models.URLField(help_text='URL to the Wikipedia article')),
                ('summary', models.TextField(help_text='Article summary/extract')),
                ('last_updated', models.DateTimeField(help_text='When the Wikipedia article was last updated')),
            ],
            options={
                'verbose_name': 'Wikipedia data',
                'verbose_name_plural': 'Wikipedia data',
            },
            bases=('artefacts.artefactdata',),
        ),
        migrations.AddField(
            model_name='artefactdata',
            name='artefact',
            field=models.ForeignKey(help_text='The artefact this data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='artefacts.artefact'),
        ),
        migrations.AddField(
            model_name='artefactdata',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='artefactenrichmenttask',
            name='artefact',
            field=models.ForeignKey(help_text='The artefact to be enriched', on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_tasks', to='artefacts.artefact'),
        ),
        migrations.AddField(
            model_name='artefactenrichmenttask',
            name='result_data',
            field=models.ForeignKey(blank=True, help_text='The ArtefactData instance created/updated by this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creation_task', to='artefacts.artefactdata'),
        ),
        migrations.AddIndex(
            model_name='artefact',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='artefact_embedding_idx', opclasses=['vector_l2_ops']),
        ),
        migrations.AddIndex(
            model_name='artefactlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='artefacts_a_latitud_2dabe1_idx'),
        ),
        migrations.AddIndex(
            model_name='artefactmedia',
            index=models.Index(fields=['type'], name='artefacts_a_type_938ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='artefacttemporalcontext',
            index=models.Index(fields=['start_date', 'end_date'], name='artefacts_a_start_d_cd6fe6_idx'),
        ),
        migrations.AddField(
            model_name='artefactwikidatarelation',
            name='related_artefact',
            field=models.ForeignKey(help_text='The artefact this one is related to', on_delete=django.db.models.deletion.CASCADE, related_name='wikidata_relations_to', to='artefacts.artefact'),
        ),
        migrations.AddIndex(
            model_name='artefactattribute',
            index=models.Index(fields=['artefact', 'source'], name='artefacts_a_artefac_65601f_idx'),
        ),
        migrations.AddIndex(
            model_name='artefactgoogleplacedata',
            index=models.Index(fields=['place_id'], name='artefacts_a_place_i_ff079a_idx'),
        ),
        migrations.AddIndex(
            model_name='artefactgoogleplacedata',
            index=models.Index(fields=['rating'], name='artefacts_a_rating_855987_idx'),
        ),
        migrations.AddIndex(
            model_name='artefacttripadvisordata',
            index=models.Index(fields=['location_id'], name='artefacts_a_locatio_1ea487_idx'),
        ),
        migrations.AddIndex(
            model_name='artefacttripadvisordata',
            index=models.Index(fields=['rating'], name='artefacts_a_rating_951bed_idx'),
        ),
        migrations.AddIndex(
            model_name='artefactwikidatadata',
            index=models.Index(fields=['entity_id'], name='artefacts_a_entity__d0470e_idx'),
        ),
        migrations.AddIndex(
            model_name='artefactwikipediadata',
            index=models.Index(fields=['page_id'], name='artefacts_a_page_id_a06659_idx'),
        ),
        migrations.AddIndex(
            model_name='artefactdata',
            index=models.Index(fields=['artefact', 'fetched_at'], name='artefacts_a_artefac_218cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='artefactenrichmenttask',
            index=models.Index(fields=['state', 'created_at'], name='artefacts_a_state_8cc60f_idx'),
        ),
        migrations.AddIndex(
            model_name='artefactenrichmenttask',
            index=models.Index(fields=['artefact', 'data_type'], name='artefacts_a_artefac_470e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='artefactenrichmenttask',
            index=models.Index(fields=['state', 'retry_count'], name='artefacts_a_state_8b14f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='artefactenrichmenttask',
            unique_together={('artefact', 'data_type', 'state')},
        ),
        migrations.AddIndex(
            model_name='artefactwikidatarelation',
            index=models.Index(fields=['property_id'], name='artefacts_a_propert_842c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='artefactwikidatarelation',
            index=models.Index(fields=['confidence'], name='artefacts_a_confide_df9f3e_idx'),
        ),
    ]
