# Generated by Django 5.1.3 on 2024-12-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialties', models.JSONField(default=list, help_text='Areas of expertise (e.g., historical sites, cultural experiences)')),
                ('teaching_style', models.TextField(help_text='Natural approach to guiding others', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Satori',
                'verbose_name_plural': 'Satori',
            },
        ),
    ]
