# Generated by Django 5.1.3 on 2024-11-29 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chats.message')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('chats.message',),
        ),
        migrations.CreateModel(
            name='HumanMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chats.message')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('chats.message',),
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='updated_at',
        ),
    ]
