# Generated by Django 5.1.3 on 2024-11-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_botmessage_humanmessage_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
    ]
