# Generated by Django 5.1.3 on 2025-01-09 14:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(help_text='The overarching theme or atmosphere of this dojo')),
                ('principles', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, help_text='Core principles that guide interactions', size=None)),
                ('ronin_system_message', models.TextField(help_text="System message that shapes the Ronin's personality and approach")),
                ('satori_system_message', models.TextField(help_text="System message that shapes the Satori's personality and approach")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
