# Generated by Django 5.1.3 on 2024-12-22 07:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='principles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, help_text='Core principles that guide interactions', size=None),
        ),
        migrations.AddField(
            model_name='dojo',
            name='ronin_system_message',
            field=models.TextField(default='', help_text="System message that shapes the Ronin's personality and approach"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dojo',
            name='satori_system_message',
            field=models.TextField(default='', help_text="System message that shapes the Satori's personality and approach"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dojo',
            name='theme',
            field=models.TextField(default='', help_text='The overarching theme or atmosphere of this dojo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dojo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
