# Generated by Django 5.1.3 on 2024-12-22 13:36

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The actual text of the entity', max_length=255)),
                ('confidence', models.FloatField(help_text='Confidence score of the entity detection')),
                ('start_position', models.IntegerField(help_text='Starting position of the entity in the message text')),
                ('end_position', models.IntegerField(help_text='Ending position of the entity in the message text')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, help_text='The vector embedding for this entity instance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['-confidence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityArchetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of this archetype (e.g., 'Location.Geographic')", max_length=100)),
                ('description', models.TextField(help_text='Description of what this archetype represents and examples')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, help_text="The vector embedding representing this archetype's essence")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
