# Generated by Django 5.1.3 on 2024-12-21 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('mondos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='message',
            field=models.ForeignKey(help_text='The message containing this entity', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='mondos.message'),
        ),
        migrations.AddField(
            model_name='entityarchetype',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent archetype if this is a sub-type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='entities.entityarchetype'),
        ),
        migrations.AddField(
            model_name='entity',
            name='archetype',
            field=models.ForeignKey(help_text='The archetype this entity belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='detected_entities', to='entities.entityarchetype'),
        ),
        migrations.AddField(
            model_name='referenceentity',
            name='archetype',
            field=models.ForeignKey(help_text='The archetype this reference entity belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='reference_entities', to='entities.entityarchetype'),
        ),
        migrations.AddField(
            model_name='referenceentity',
            name='mondo',
            field=models.ForeignKey(help_text='The mondo that created this reference entity', on_delete=django.db.models.deletion.CASCADE, related_name='reference_entities', to='mondos.mondo'),
        ),
        migrations.AddField(
            model_name='entity',
            name='reference_entity',
            field=models.ForeignKey(help_text='The reference entity this was matched against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_entities', to='entities.referenceentity'),
        ),
        migrations.AddIndex(
            model_name='entityarchetype',
            index=models.Index(fields=['name'], name='entities_en_name_fb046a_idx'),
        ),
        migrations.AddIndex(
            model_name='entityarchetype',
            index=models.Index(fields=['parent'], name='entities_en_parent__b1bc7c_idx'),
        ),
        migrations.RunSQL(
            sql="""
            -- Create HNSW indexes with optimized parameters
            CREATE INDEX archetype_embedding_idx ON entities_entityarchetype 
            USING hnsw (embedding vector_l2_ops) 
            WITH (m = 16, ef_construction = 64);

            CREATE INDEX reference_embedding_idx ON entities_referenceentity 
            USING hnsw (embedding vector_l2_ops) 
            WITH (m = 16, ef_construction = 64);

            CREATE INDEX entity_embedding_idx ON entities_entity 
            USING hnsw (embedding vector_l2_ops) 
            WITH (m = 16, ef_construction = 64);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS archetype_embedding_idx;
            DROP INDEX IF EXISTS reference_embedding_idx;
            DROP INDEX IF EXISTS entity_embedding_idx;
            """
        ),
        migrations.AddIndex(
            model_name='referenceentity',
            index=models.Index(fields=['text'], name='entities_re_text_eeb10e_idx'),
        ),
        migrations.AddIndex(
            model_name='referenceentity',
            index=models.Index(fields=['archetype'], name='entities_re_archety_64d73d_idx'),
        ),
        migrations.AddIndex(
            model_name='referenceentity',
            index=models.Index(fields=['mondo'], name='entities_re_mondo_i_d07665_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['text'], name='entities_en_text_13e0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['archetype'], name='entities_en_archety_78b160_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['message'], name='entities_en_message_f2af91_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['confidence'], name='entities_en_confide_e70723_idx'),
        ),
    ]
