# Generated by Django 5.1.3 on 2024-12-22 13:36

import django.db.models.deletion
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('mondos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='message',
            field=models.ForeignKey(help_text='The message containing this entity', on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='mondos.message'),
        ),
        migrations.AddField(
            model_name='entityarchetype',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent archetype if this is a sub-type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='entities.entityarchetype'),
        ),
        migrations.AddField(
            model_name='entity',
            name='archetype',
            field=models.ForeignKey(help_text='The archetype this entity belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='detected_entities', to='entities.entityarchetype'),
        ),
        migrations.AddField(
            model_name='entityreference',
            name='mondo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_references', to='mondos.mondo'),
        ),
        migrations.AddField(
            model_name='entity',
            name='reference_entity',
            field=models.ForeignKey(help_text='The reference entity this was matched against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_entities', to='entities.entityreference'),
        ),
        migrations.AddIndex(
            model_name='entityarchetype',
            index=models.Index(fields=['name'], name='entities_en_name_fb046a_idx'),
        ),
        migrations.AddIndex(
            model_name='entityarchetype',
            index=models.Index(fields=['parent'], name='entities_en_parent__b1bc7c_idx'),
        ),
        migrations.AddIndex(
            model_name='entityarchetype',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='archetype_embedding_idx', opclasses=['vector_l2_ops']),
        ),
        migrations.AddIndex(
            model_name='entityreference',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='reference_embedding_idx', opclasses=['vector_l2_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='entityreference',
            unique_together={('text', 'type', 'mondo')},
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['text'], name='entities_en_text_13e0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['archetype'], name='entities_en_archety_78b160_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['message'], name='entities_en_message_f2af91_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['confidence'], name='entities_en_confide_e70723_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='entity_embedding_idx', opclasses=['vector_l2_ops']),
        ),
    ]
