# Generated by Django 5.1.3 on 2024-12-22 06:53

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_alter_entityreference_mondo'),
        ('mondos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityreference',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='entityreference',
            name='entities_re_text_eeb10e_idx',
        ),
        migrations.RemoveIndex(
            model_name='entityreference',
            name='entities_re_archety_64d73d_idx',
        ),
        migrations.RemoveIndex(
            model_name='entityreference',
            name='entities_re_mondo_i_d07665_idx',
        ),
        migrations.AddField(
            model_name='entityreference',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='entityreference',
            unique_together={('text', 'type', 'mondo')},
        ),
        migrations.AlterField(
            model_name='entityreference',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
        migrations.AlterField(
            model_name='entityreference',
            name='text',
            field=models.TextField(),
        ),
        # Drop existing vector indexes if they exist
        migrations.RunSQL(
            sql="""
            DROP INDEX IF EXISTS entity_embedding_idx;
            DROP INDEX IF EXISTS archetype_embedding_idx;
            DROP INDEX IF EXISTS reference_embedding_idx;
            """,
            reverse_sql="",
        ),
        # Create new vector indexes with proper HNSW configuration
        migrations.RunSQL(
            sql="""
            CREATE INDEX entity_embedding_idx ON entities_entity 
            USING hnsw (embedding vector_l2_ops) 
            WITH (m = 16, ef_construction = 64);

            CREATE INDEX archetype_embedding_idx ON entities_entityarchetype 
            USING hnsw (embedding vector_l2_ops) 
            WITH (m = 16, ef_construction = 64);

            CREATE INDEX reference_embedding_idx ON entities_entityreference 
            USING hnsw (embedding vector_l2_ops) 
            WITH (m = 16, ef_construction = 64);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS entity_embedding_idx;
            DROP INDEX IF EXISTS archetype_embedding_idx;
            DROP INDEX IF EXISTS reference_embedding_idx;
            """
        ),
        migrations.RemoveField(
            model_name='entityreference',
            name='archetype',
        ),
    ]
