# Generated by Django 5.1.3 on 2024-12-22 06:53

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_entityreference_options_and_more'),
    ]

    operations = [
        # First ensure pgvector extension is installed
        CreateExtension('vector'),
        
        # Drop existing indexes if they exist
        migrations.RunSQL(
            sql="""
            DROP INDEX IF EXISTS entity_embedding_idx;
            DROP INDEX IF EXISTS archetype_embedding_idx;
            DROP INDEX IF EXISTS reference_embedding_idx;
            """,
            reverse_sql=""
        ),
        
        # Create vector indexes with HNSW
        migrations.RunSQL(
            sql="""
            CREATE INDEX entity_embedding_idx ON entities_entity 
            USING hnsw (embedding vector_l2_ops) 
            WITH (m = 16, ef_construction = 64);

            CREATE INDEX archetype_embedding_idx ON entities_entityarchetype 
            USING hnsw (embedding vector_l2_ops) 
            WITH (m = 16, ef_construction = 64);

            CREATE INDEX reference_embedding_idx ON entities_entityreference 
            USING hnsw (embedding vector_l2_ops) 
            WITH (m = 16, ef_construction = 64);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS entity_embedding_idx;
            DROP INDEX IF EXISTS archetype_embedding_idx;
            DROP INDEX IF EXISTS reference_embedding_idx;
            """
        ),
    ]
